const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const midiHz=n=>440*Math.pow(2,(n-69)/12);
const waves={triangle:'triangle',shark:'sawtooth',sawtooth:'sawtooth',square:'square',wide:'square',narrow:'square',reverse:'sawtooth'};
const ranges={LO:0.25,"32'":2,"16'":1,"8'":0.5,"4'":0.25,"2'":0.125};
const defaults={tune:0,glide:0,modMix:0,oscMod:false,osc3Control:true,osc1Range:"8'",osc1Wave:'sawtooth',osc2Range:"8'",osc2Freq:0,osc2Wave:'sawtooth',osc3Range:"8'",osc3Freq:0,osc3Wave:'sawtooth',osc1On:true,osc1Vol:8,extOn:false,extVol:5,osc2On:false,osc2Vol:8,noiseOn:false,noiseVol:8,noiseType:'white',osc3On:false,osc3Vol:8,filterMod:false,key1:true,key2:false,cutoff:0,emphasis:0,contourAmount:5,filterAttack:0,filterDecay:4,filterSustain:5,loudAttack:0,loudDecay:4,loudSustain:8,volume:8,a440:false,glideOn:false,decayOn:true,pitch:0,modWheel:0,bendRange:2,poly:false,voices:4,entropy:0,spread:0,feedback:0,lock:false};
function makeVoice(ctx,p){const g=ctx.createGain(),filter=ctx.createBiquadFilter(),amp=ctx.createGain(),pan=ctx.createStereoPanner(); filter.type='lowpass'; g.connect(filter).connect(amp).connect(pan).connect(ctx.destination); amp.gain.value=0; const os=[]; [1,2,3].forEach(i=>{const o=ctx.createOscillator(),og=ctx.createGain();o.type=waves[p['osc'+i+'Wave']]||'sawtooth';o.connect(og).connect(g);og.gain.value=0; o.start();os.push({o,g:og});}); const noise=ctx.createBufferSource(); const nb=ctx.createBuffer(ctx.sampleRate*2,ctx.sampleRate*2,ctx.sampleRate);const d=nb.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;noise.buffer=nb;noise.loop=true;const ng=ctx.createGain();ng.gain.value=0;noise.connect(ng).connect(g);noise.start();return {g,filter,amp,pan,os,ng,noise,note:-1};}
export class CA72Audio{
 constructor(){this.ctx=null;this.voices=[];this.p=structuredClone(defaults);this.active=new Map();}
 async start(){if(!this.ctx)this.ctx=new (window.AudioContext||window.webkitAudioContext)();await this.ctx.resume();this.rebuild();}
 rebuild(){this.voices.forEach(v=>{try{v.os.forEach(x=>x.o.stop())}catch{}try{v.noise.stop()}catch{}});this.voices=[];const n=this.p.poly?this.p.voices:1;for(let i=0;i<n;i++)this.voices.push(makeVoice(this.ctx,this.p));}
 set(k,v){this.p[k]=v;if(k==='poly'||k==='voices'){this.rebuild();return}this.voices.forEach(v=>this.apply(v));}
 apply(v){if(!this.ctx)return;const now=this.ctx.currentTime;const p=this.p;for(let i=1;i<=3;i++){const x=v.os[i-1],on=p['osc'+i+'On'],freq=p['osc'+i+'Freq'];x.o.type=waves[p['osc'+i+'Wave']]||'sawtooth';const range=ranges[p['osc'+i+'Range']]||.5;x.g.gain.setTargetAtTime(on?p['osc'+i+'Vol']/10:0,now,.01);if(v.note>=0)x.o.frequency.setTargetAtTime(midiHz(v.note)*range*Math.pow(2,(i===1?0:freq)/12),now,.01)}v.ng.gain.setTargetAtTime(p.noiseOn?p.noiseVol/30:0,now,.01);v.filter.frequency.setTargetAtTime(120+Math.pow(2,(p.cutoff+5)/10*10)*45,now,.015);v.filter.Q.setTargetAtTime(p.emphasis*1.2,now,.02);v.amp.gain.setTargetAtTime(p.volume/10,now,.01);}
 noteOn(note,velocity=1){if(!this.ctx)return;let v=this.voices.find(x=>x.note<0)||this.voices[0];if(!v)return;v.note=note;const now=this.ctx.currentTime;v.amp.gain.cancelScheduledValues(now);v.amp.gain.setValueAtTime(0,now);const a=Math.max(.002,this.p.loudAttack/10),d=Math.max(.02,this.p.loudDecay/2),s=this.p.loudSustain/10;v.amp.gain.linearRampToValueAtTime(Math.max(.001,velocity)*this.p.volume/10,now+a);v.amp.gain.linearRampToValueAtTime(s*this.p.volume/10,now+a+d);this.apply(v);this.active.set(note,v);}
 noteOff(note){const v=this.active.get(note);if(!v)return;const now=this.ctx.currentTime;v.amp.gain.cancelScheduledValues(now);v.amp.gain.setTargetAtTime(0,now,.08+this.p.filterDecay/20);v.note=-1;this.active.delete(note);}
 pitch(x){this.p.pitch=x;this.voices.forEach(v=>v.os.forEach((o,i)=>{if(v.note>=0)o.o.detune.setTargetAtTime(x*this.p.bendRange*100, this.ctx.currentTime,.01)}));}
 getPreset(){return structuredClone(this.p)} setPreset(p){this.p={...defaults,...p};this.rebuild();this.voices.forEach(v=>this.apply(v));}
}
export {defaults};