import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{CA72Audio,ranges}from'./audio';import'./styles.css';
const audio=new CA72Audio();
const keys=[{n:60,l:'C'},{n:61,l:'C#'},{n:62,l:'D'},{n:63,l:'D#'},{n:64,l:'E'},{n:65,l:'F'},{n:66,l:'F#'},{n:67,l:'G'},{n:68,l:'G#'},{n:69,l:'A'},{n:70,l:'A#'},{n:71,l:'B'},{n:72,l:'C'}];
function Knob({label,k,min=0,max=10,step=.01}){const[v,setV]=useState(audio.p[k]??0);const update=x=>{setV(x);audio.set(k,x)};return <label className="knob"><span>{label}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={v} onChange={e=>update(+e.target.value)}/><b>{typeof v==='number'?v.toFixed(step<1?1:0):v}</b></label>}
function Switch({label,k}){const[v,setV]=useState(!!audio.p[k]);return <button className={`switch ${v?'on':''}`} onClick={()=>{setV(!v);audio.set(k,!v)}}>{label}</button>}
function Select({label,k,options}){const[v,setV]=useState(audio.p[k]);return <label className="select"><span>{label}</span><select value={v} onChange={e=>{setV(e.target.value);audio.set(k,e.target.value)}}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Section({title,children}){return <section><h2>{title}</h2><div className="grid">{children}</div></section>}
function App(){const[power,setPower]=useState(true);const[preset,setPreset]=useState('Init');const[drawer,setDrawer]=useState(false);const[presets,setPresets]=useState(()=>JSON.parse(localStorage.getItem('ca72-web-presets')||'[]'));const save=()=>{const p=audio.getPreset();const list=[...presets.filter(x=>x.name!==preset),{name:preset,data:p}];setPresets(list);localStorage.setItem('ca72-web-presets',JSON.stringify(list));setDrawer(false)};useEffect(()=>{const down=e=>{if(e.repeat)return;const map={z:60,s:61,x:62,d:63,c:64,v:65,g:66,b:67,h:68,n:69,j:70,m:71,',':72};if(map[e.key]!=null){audio.start();audio.noteOn(map[e.key])}};const up=e=>{const map={z:60,s:61,x:62,d:63,c:64,v:65,g:66,b:67,h:68,n:69,j:70,m:71,',':72};if(map[e.key]!=null)audio.noteOff(map[e.key])};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[]);return <main className={power?'':'off'}><header><div><small>IDLE FOUNDRY / WEB INSTRUMENT</small><h1>CA-72</h1></div><div className="status">WEB AUDIO • {audio.ctx?'RUNNING':'READY'}</div></header><div className="panel">
<div className="controls"><div className="controller"><Knob label="TUNE" k="tune" min={-2.5} max={2.5}/><Knob label="GLIDE" k="glide"/><Knob label="MOD MIX" k="modMix"/><Switch label="OSC MOD" k="oscMod"/><Switch label="OSC 3 CTRL" k="osc3Control"/></div>
<Section title="OSCILLATOR BANK"><div className="osc"><h3>OSC 1</h3><Select label="RANGE" k="osc1Range" options={Object.keys(ranges)}/><Select label="WAVE" k="osc1Wave" options={['triangle','shark','sawtooth','square','wide','narrow']}/><Switch label="ON" k="osc1On"/></div><div className="osc"><h3>OSC 2</h3><Select label="RANGE" k="osc2Range" options={Object.keys(ranges)}/><Knob label="FREQ" k="osc2Freq" min={-7.5} max={7.5}/><Select label="WAVE" k="osc2Wave" options={['triangle','shark','sawtooth','square','wide','narrow']}/><Switch label="ON" k="osc2On"/></div><div className="osc"><h3>OSC 3</h3><Select label="RANGE" k="osc3Range" options={Object.keys(ranges)}/><Knob label="FREQ" k="osc3Freq" min={-7.5} max={7.5}/><Select label="WAVE" k="osc3Wave" options={['triangle','reverse','sawtooth','square','wide','narrow']}/><Switch label="ON" k="osc3On"/></div></Section>
<Section title="MIXER"><Knob label="OSC 1" k="osc1Vol"/><Knob label="OSC 2" k="osc2Vol"/><Knob label="OSC 3" k="osc3Vol"/><Knob label="NOISE" k="noiseVol"/><Switch label="NOISE" k="noiseOn"/><Select label="NOISE COLOR" k="noiseType" options={['white','pink']}/><Switch label="EXTERNAL" k="extOn"/><Knob label="EXT VOL" k="extVol"/></Section>
<Section title="MODIFIERS"><Knob label="CUTOFF" k="cutoff" min={-5} max={5}/><Knob label="EMPHASIS" k="emphasis"/><Knob label="CONTOUR" k="contourAmount"/><Switch label="FILTER MOD" k="filterMod"/><Switch label="KEY 1" k="key1"/><Switch label="KEY 2" k="key2"/></Section>
<Section title="CONTOURS"><div><h3>FILTER</h3><Knob label="ATTACK" k="filterAttack"/><Knob label="DECAY" k="filterDecay"/><Knob label="SUSTAIN" k="filterSustain"/></div><div><h3>LOUDNESS</h3><Knob label="ATTACK" k="loudAttack"/><Knob label="DECAY" k="loudDecay"/><Knob label="SUSTAIN" k="loudSustain"/></div></Section>
<Section title="OUTPUT"><Knob label="VOLUME" k="volume"/><Switch label="A-440" k="a440"/><Switch label="GLIDE" k="glideOn"/><Switch label="DECAY" k="decayOn"/><Knob label="PITCH" k="pitch" min={-1} max={1}/><Knob label="MOD" k="modWheel"/></Section>
</div></div>
<div className="strip"><div className="preset"><button onClick={()=>setDrawer(!drawer)}>{preset} ▾</button><button onClick={save}>SAVE</button>{drawer&&<div className="drawer"><input value={preset} onChange={e=>setPreset(e.target.value)} placeholder="Preset name"/>{presets.map(x=><button key={x.name} onClick={()=>{setPreset(x.name);audio.setPreset(x.data);setDrawer(false)}}>{x.name}</button>)}</div>}</div><button className={`switch ${power?'on':''}`} onClick={()=>{setPower(!power);audio.set('power',!power)}}>{power?'POWER':'BYPASS'}</button><Switch label="POLY" k="poly"/><Knob label="VOICES" k="voices" min={2} max={10} step={1}/><Knob label="ENTROPY" k="entropy" min={0} max={100}/><Knob label="SPREAD" k="spread" min={0} max={100}/><Knob label="FEEDBACK" k="feedback"/></div>
<div className="keyboard">{keys.map(k=><button key={k.n} className={k.l.includes('#')?'black':''} onPointerDown={e=>{e.preventDefault();audio.start();audio.noteOn(k.n)}} onPointerUp={()=>audio.noteOff(k.n)} onPointerLeave={()=>audio.noteOff(k.n)}>{k.l}</button>)}</div><footer>Keyboard: Z–, • WebAudio • local presets • no backend</footer></main>}
createRoot(document.getElementById('root')).render(<App/>);